### ISSUE TITLE
TODO-list before publishing FOSS4G2022 article

### ISSUE THREAD

**Issue by nicolas-roelandt** [nicolas-roelandt/lasso-data-analysis#3]
- [ ] transfert repo to [Univ. Eiffel/IFSTTAR organisation](https://github.com/Ifsttar/)
- [ ] write article's abstract
- [ ] write article's conclusion
- [ ] update links
- [ ] work on literate programming / FOSS benefits

**Comment by pierromond** [comment]
- [ ] write Pierre part ;) about environnemental acoustics and noisecapture :) haha

**Comment by nicolas-roelandt** [comment]
@pierromond, est-ce qu'on introduit une partie Discussion/limites ?
